/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Alive
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-02T10:50:49.423+01:00")
public class Alive {
  @SerializedName("isAlive")
  private String isAlive = null;

  @SerializedName("pid")
  private String pid = null;

  public Alive isAlive(String isAlive) {
    this.isAlive = isAlive;
    return this;
  }

   /**
   * Get isAlive
   * @return isAlive
  **/
  @ApiModelProperty(value = "")
  public String getIsAlive() {
    return isAlive;
  }

  public void setIsAlive(String isAlive) {
    this.isAlive = isAlive;
  }

  public Alive pid(String pid) {
    this.pid = pid;
    return this;
  }

   /**
   * Get pid
   * @return pid
  **/
  @ApiModelProperty(value = "")
  public String getPid() {
    return pid;
  }

  public void setPid(String pid) {
    this.pid = pid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Alive alive = (Alive) o;
    return Objects.equals(this.isAlive, alive.isAlive) &&
        Objects.equals(this.pid, alive.pid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isAlive, pid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Alive {\n");
    
    sb.append("    isAlive: ").append(toIndentedString(isAlive)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

